"""
Seed script: inserts 15 sample companies across sectors and pipeline stages.
Run from apps/api with venv active: python seed.py
"""
import asyncio
from app.database import AsyncSessionLocal
from app.models.company import Company, PipelineStage, OwnershipType


SEED_COMPANIES = [
    {
        "name": "Rocky Mountain IVF Center",
        "website": "https://rmivf.com",
        "hq_location": "Denver, CO",
        "sector": "IVF",
        "stage": PipelineStage.Engaged,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 45,
        "ebitda_low": 2_500_000,
        "ebitda_high": 3_500_000,
        "source": "LinkedIn",
    },
    {
        "name": "Pinnacle Self-Directed IRA Services",
        "website": "https://pinnaclesira.com",
        "hq_location": "Phoenix, AZ",
        "sector": "SDIRA",
        "stage": PipelineStage.OutreachSent,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 22,
        "ebitda_low": 1_800_000,
        "ebitda_high": 2_800_000,
        "source": "Referral — Saheb",
    },
    {
        "name": "Meridian Accounting Group",
        "website": "https://meridianaccounting.com",
        "hq_location": "Nashville, TN",
        "sector": "Accounting",
        "stage": PipelineStage.NDASigned,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 38,
        "ebitda_low": 3_000_000,
        "ebitda_high": 4_500_000,
        "source": "M&A Broker",
        "notes": "Owner retiring in 18 months. Very motivated.",
    },
    {
        "name": "SunState HOA Management",
        "website": "https://sunstatehoa.com",
        "hq_location": "Tampa, FL",
        "sector": "HOA",
        "stage": PipelineStage.Identified,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 60,
        "ebitda_low": 2_000_000,
        "ebitda_high": 3_000_000,
        "source": "Google Maps scrape",
    },
    {
        "name": "ClearPath Revenue Cycle",
        "website": "https://clearpathrcm.com",
        "hq_location": "Atlanta, GA",
        "sector": "RCM",
        "stage": PipelineStage.Engaged,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 85,
        "ebitda_low": 4_000_000,
        "ebitda_high": 6_000_000,
        "source": "Industry conference",
        "notes": "Met at HFMA. CEO open to strategic conversations.",
    },
    {
        "name": "Apex Defense Logistics",
        "website": "https://apexdefenselogistics.com",
        "hq_location": "Huntsville, AL",
        "sector": "Defense",
        "stage": PipelineStage.Identified,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 120,
        "ebitda_low": 5_000_000,
        "ebitda_high": 8_000_000,
        "source": "FPDS scrape",
    },
    {
        "name": "Great Plains IVF Associates",
        "website": "https://greatplainsfertility.com",
        "hq_location": "Omaha, NE",
        "sector": "IVF",
        "stage": PipelineStage.Identified,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 30,
        "ebitda_low": 2_000_000,
        "ebitda_high": 3_000_000,
        "source": "Web research",
    },
    {
        "name": "Heritage Self-Directed Retirement",
        "website": "https://heritagesdira.com",
        "hq_location": "Salt Lake City, UT",
        "sector": "SDIRA",
        "stage": PipelineStage.LOISubmitted,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 18,
        "ebitda_low": 1_500_000,
        "ebitda_high": 2_200_000,
        "source": "Direct outreach",
        "notes": "LOI submitted 2/10. Owner reviewing. Follow up 2/24.",
    },
    {
        "name": "BlueSky CPA & Advisory",
        "website": "https://blueskycpa.com",
        "hq_location": "Austin, TX",
        "sector": "Accounting",
        "stage": PipelineStage.OutreachSent,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 25,
        "ebitda_low": 1_200_000,
        "ebitda_high": 2_000_000,
        "source": "LinkedIn",
    },
    {
        "name": "Premier Community Management",
        "website": "https://premiercommunity.com",
        "hq_location": "Scottsdale, AZ",
        "sector": "HOA",
        "stage": PipelineStage.Engaged,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 75,
        "ebitda_low": 3_500_000,
        "ebitda_high": 5_000_000,
        "source": "Referral — John",
    },
    {
        "name": "Delta Medical Billing Services",
        "website": "https://deltamedicalbilling.com",
        "hq_location": "Dallas, TX",
        "sector": "RCM",
        "stage": PipelineStage.Diligence,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 110,
        "ebitda_low": 5_500_000,
        "ebitda_high": 7_500_000,
        "source": "M&A Broker",
        "notes": "In active diligence. QoE underway with RSM.",
    },
    {
        "name": "Ironclad Systems Integration",
        "website": "https://ironclaidsys.com",
        "hq_location": "Colorado Springs, CO",
        "sector": "Defense",
        "stage": PipelineStage.OutreachSent,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 55,
        "ebitda_low": 3_000_000,
        "ebitda_high": 4_500_000,
        "source": "FPDS scrape",
    },
    {
        "name": "Coastal Fertility Specialists",
        "website": "https://coastalfertility.com",
        "hq_location": "San Diego, CA",
        "sector": "IVF",
        "stage": PipelineStage.Passed,
        "ownership_type": OwnershipType.PEBacked,
        "employee_count": 65,
        "ebitda_low": 6_000_000,
        "ebitda_high": 9_000_000,
        "source": "M&A Broker",
        "notes": "Already PE-backed. Passed — revisit post-recapitalization.",
    },
    {
        "name": "Lakewood Associates CPA",
        "website": "https://lakewoodcpa.com",
        "hq_location": "Minneapolis, MN",
        "sector": "Accounting",
        "stage": PipelineStage.Identified,
        "ownership_type": OwnershipType.FounderOwned,
        "employee_count": 20,
        "ebitda_low": 900_000,
        "ebitda_high": 1_400_000,
        "source": "LinkedIn",
        "notes": "Small but high-margin. Monitor for growth.",
    },
    {
        "name": "Summit HOA Solutions",
        "website": "https://summithoasolutions.com",
        "hq_location": "Denver, CO",
        "sector": "HOA",
        "stage": PipelineStage.OnHold,
        "ownership_type": OwnershipType.FamilyOwned,
        "employee_count": 40,
        "ebitda_low": 1_800_000,
        "ebitda_high": 2_500_000,
        "source": "Direct outreach",
        "notes": "Owner going through family health issue. Revisit Q3 2026.",
    },
]


async def seed():
    async with AsyncSessionLocal() as db:
        for data in SEED_COMPANIES:
            company = Company(**data)
            db.add(company)
        await db.commit()
        print(f"Seeded {len(SEED_COMPANIES)} companies.")


if __name__ == "__main__":
    asyncio.run(seed())
